language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - python tests/test_baselines.py
  - python tests/test_optimizers.py
  - python tests/test_policies.py
  - python tests/test_samplers.py